apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimizer
  namespace: taler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimizer-admin
subjects:
- kind: ServiceAccount
  name: optimizer
  namespace: taler
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer
  namespace: taler
  labels:
    app: optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizer
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      serviceAccountName: optimizer
      containers:
      - name: optimizer
        image: ${OPTIMIZER_IMAGE}  # This is a placeholder that will be replaced by the Makefile
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
