apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: taler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-client
  namespace: taler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-client
  template:
    metadata:
      labels:
        app: echo-client
    spec:
      serviceAccountName: test-app-sa
      containers:
        - name: echo-client
          image: ghcr.io/tsonov/cast-taler/echo:latest
          imagePullPolicy: Always
          args:
            - --module
            - echo-client
            - --echo-server-ip
            - echo-server
            - "--echo-allow-reconnect"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-server
  name: echo-server
  namespace: taler
spec:
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - args:
            - --module
            - echo-server
            - --module
            - memory
            - --initial-allocation
            - "1024"
            - "--echo-allow-reconnect"
          image: ghcr.io/tsonov/cast-taler/echo:latest
          imagePullPolicy: Always
          name: echo-server
          ports:
            - containerPort: 8080
              name: tcp
            - containerPort: 10000
              name: udp
            - containerPort: 9090
              name: prom
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: taler
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp-test
    - port: 9090
      protocol: TCP
      targetPort: 9090
      name: prom
    - port: 10000
      protocol: UDP
      targetPort: 10000
      name: udp-test
  selector:
    app: echo-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-app-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: test-app-sa
    namespace: taler